security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: account
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
    #  url: mongodb://cloud:123456@localhost:27017/cloud
      url: mongodb://localhost:27017/cloud
      database: cloud
    #  authenticationDatabase: cloud
    #   username: cloud
    #   password: 123456

server:
  context-path: /accounts
  port: 6000
