spring:
  data:
    mongodb:
      #uri: mongodb://cloud:123456@localhost:27017/cloud
      uri: '{cipher}a6aefc869c9e37519213feedb9333a7a962b6c2215bb9532cbbd4ce5cdb4e5b7b72331f0b501f5208d7d9c88d7c1e89583984434b85177faaa8a11a970b49000'

# mongodb3.0 客户端后，host，port无效 https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/#boot-features-mongodb

server:
  context-path: /uaa
  port: 5000

security:
  oauth2:
    resource:
      filter-order: 3