security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: statistics
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      uri: mongodb://cloud:123456@localhost:27017/cloud

server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io